version: 0.2

env:
  shell: bash
  variables:
    PACKAGE_VERSION: "1.0.0"
    PACKAGE_NAME: "aws-clickstream-android"
phases:
  install:
    runtime-versions:
      java: corretto21
  pre_build:
    commands:
      - |-
        set -euxo pipefail
        echo "=== Download Android command line tools ==="
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        unzip commandlinetools-linux-11076708_latest.zip
        mkdir android_sdk
        mv cmdline-tools android_sdk/
        echo "=== Install Android SDK platform and build tools"
        echo "y" | android_sdk/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/Android/Sdk --licenses
        echo "y" | android_sdk/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/Android/Sdk "platforms;android-33" "platform-tools" "build-tools;33.0.0"
        export ANDROID_SDK_ROOT=$HOME/Android/Sdk
        rm -rf android_sdk/
        rm -f commandlinetools-linux-11076708_latest.zip
  build:
    commands:
      - BUILD_DIR=$(pwd)
      - echo "=== Run Open Source Dist & S3 Dist @ $(date) in $(pwd) ==="
      - cd deployment
      - chmod +x ./build-s3-dist.sh && ./build-s3-dist.sh --template-bucket ${TEMPLATE_OUTPUT_BUCKET} --version ${VERSION} --region ${AWS_REGION}
      - echo "Starting open-source-dist `date` in `pwd`"
      - chmod +x ./build-open-source-dist.sh && ./build-open-source-dist.sh $SOLUTION_NAME
      - cd $BUILD_DIR
      - chmod +x gradlew
      - echo "=== Run unit tests ==="
      - ./gradlew clean && rm -rf .gradle
      - ./gradlew jacocoTestReport
      - echo "=== Build Clickstream Android SDK with Gradle ==="
      - ./gradlew clean && rm -rf .gradle
      - ./gradlew build -p clickstream
  post_build:
    commands:
      - echo "=== Starting Post-Build Phase ==="

artifacts:
  exclude-paths:
    - .nightswatch/**/*
  files:
    - '**/*'
