name: Bug report
description: Create a report to help us improve Clickstream Android

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Try to include as much information as you can.
  - type: markdown
    attributes:
      value: |
        For reference, the current versions of the Clickstream Android packages are listed below. Please verify your issue against the latest version(s) of the relevant package(s).

        | Package                                                | Version                                                                                                          |
        | ------------------------------------------------------ | ---------------------------------------------------------------------------------------------------------------- |
        | `software.aws.solution:clickstream`                    | [![Maven Central](https://img.shields.io/maven-central/v/software.aws.solution/clickstream.svg)](https://search.maven.org/artifact/software.aws.solution/clickstream)|

  - type: checkboxes
    attributes:
      label: |
        Before opening, please confirm:
      options:
        - label: I have [searched for duplicate or closed issues](https://github.com/awslabs/clickstream-android/issues?q=is%3Aissue+).
          required: true

  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: dropdown
    attributes:
      label: Language and Async Model
      description: What programming language is being used?
      multiple: true
      options:
        - Java
        - Kotlin
        - Kotlin - Coroutines
        - RxJava
        - Not applicable
    validations:
      required: true
  - type: textarea
    attributes:
      label: Gradle script dependencies
      description: |
        Please provide the version of Clickstream being used from your `build.gradle (Module: app)` file.
      value: |
        <details>

        ```groovy
        // Put output below this line


        ```

        </details>
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment information
      description: |
        Please run the following command inside your project and copy/paste the output below:
        ```
          ./gradlew --version
        ```
      value: |
        <details>

        ```
        # Put output below this line


        ```

        </details>
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Details
  - type: input
    attributes:
      label: Please include any relevant guides or documentation you're referencing
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction steps (if applicable)
      description: |
        How do you trigger this bug? Please walk us through it step by step. Screenshots can be attached in textarea below.
      placeholder: |
        1. Install '...'
        2. Configure '...'
        3. Go to '...'
        4. See error
  - type: textarea
    attributes:
      label: Code Snippet
      description: |
        Please provide a code snippet or a link to sample code of the issue you are experiencing to help us reproduce the issue. 

        **Be sure to remove any sensitive data.**
      value: |
        ```java
        // Put your code below this line.

        ```
  - type: textarea
    attributes:
      label: Log output
      description: |
        For example, error messages, or stack traces.
        **Be sure to remove any sensitive data.**
      value: |
        <details>

        ```
        // Put your logs below this line


        ```

        </details>

  - type: textarea
    attributes:
      label: Additional information and screenshots
      description: |
        If you have any additional information, workarounds, etc. for us, use the field below.
        Please note, you can attach screenshots or screen recordings here, by
        dragging and dropping files in the field below.