name: Feature request
description: Create a feature request to help us improve Clickstream Android

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request! Try to include as much information as you can.
  - type: markdown
    attributes:
      value: |
        For reference, the current versions of the Clickstream Android are listed below. Please verify your issue against the latest version(s) of the relevant package(s).
        
        | Package                                                | Version                                                                                                          |
        | ------------------------------------------------------ | ---------------------------------------------------------------------------------------------------------------- |
        | `software.aws.solution:clickstream`                    | [![Maven Central](https://img.shields.io/maven-central/v/software.aws.solution/clickstream.svg)](https://search.maven.org/artifact/software.aws.solution/clickstream)| 

  - type: checkboxes
    attributes:
      label: |
        Before opening, please confirm:
      options:
        - label: I have [searched for duplicate or closed issues](https://github.com/awslabs/clickstream-android/issues?q=is%3Aissue+).
          required: true

  - type: textarea
    id: description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
