name: Android SDK Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: gradle
      - name: config key.properties
        run: |
          echo "nexusUsername=$NEXUS_USERNAME" >> key.properties
          echo "nexusPassword=$NEXUS_PASSWORD" >> key.properties
          echo "signing.keyId==$SIGNING_KEY_ID" >> key.properties
          echo "signing.password=$SIGNING_PASSWORD" >> key.properties
          echo "signing.inMemoryKey=$SIGNING_IN_MEMORY_KEY" >> key.properties
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build -p clickstream
      - name: Generate test report
        run: ./gradlew jacocoTestReport
      - name: Upload test result
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-result
          path: |
            clickstream/build/reports/
            clickstream/build/test-results/
      - name: Upload aar
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: aar
          path: clickstream/build/outputs/aar/
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Java Tests
          path: clickstream/build/test-results/testDebugUnitTest/TEST-*.xml
          reporter: java-junit
      - name: JaCoCo Code Coverage Report
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@v4.8
        if: success() || failure()
        with:
          coverage_results_path: clickstream/build/reports/jacoco/jacoco.xml
          coverage_report_name: Coverage
          coverage_report_title: JaCoCo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_check_run: false
          minimum_coverage: 80
          fail_below_threshold: false
          publish_only_summary: true
      - name: Add Coverage Job Summary
        run: echo "${{ steps.jacoco_reporter.outputs.coverageSummary }}" >> $GITHUB_STEP_SUMMARY