name: Run Code coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Generate test report
        run: ./gradlew jacocoTestReport
      - name: Upload test result
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-result
          path: |
            clickstream/build/reports/
            clickstream/build/test-results/
      - name: Upload Test Report
        uses: codecov/codecov-action@v3
        with:
          name: report
          files: clickstream/build/reports/jacoco/jacoco.xml