name: Publish To Maven

on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'corretto'
          cache: gradle
      - name: Config properties
        run: |
          echo "nexusUsername=${{ vars.NEXUS_USERNAME }}" >> key.properties
          echo "nexusPassword=${{ secrets.NEXUS_PASSWORD }}" >> key.properties
          echo "signing.keyId=${{ vars.SIGNING_KEY_ID }}" >> key.properties
          echo "signing.password=${{ secrets.SIGNING_PASSWORD }}" >> key.properties
          echo "signing.inMemoryKey=${{ secrets.SIGNING_IN_MEMORY_KEY }}" >> key.properties
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Assemble release
        run: ./gradlew assembleRelease
      - name: Publish to maven
        run: ./gradlew publish -p clickstream