name: Release Next Version
on:
  push:
    branches: [ "*" ]

jobs:
  release:
    if: ${{ startsWith(github.event.head_commit.message, 'release:') }}
    runs-on: ubuntu-latest
    env:
      COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.PROJECT_TOKEN }}
      - name: Create new tag
        run: |
          version=$(echo "${{ env.COMMIT_MESSAGE }}" | grep -oP 'Android \K\d+\.\d+\.\d+')
          echo $version
#          git config user.name '${{ vars.USER_NAME }}'
#          git config user.email '${{ vars.USER_EMAIL }}'
#          git tag v${{ env.NEW_VERSION }}
#          git push origin v$version
#      - name: Assemble release
#        run: |
#          chmod +x gradlew
#          ./gradlew assembleRelease
#      - name: Create GitHub release
#        uses: softprops/action-gh-release@v1
#        with:
#          name: "Clickstream Android ${{ env.NEW_VERSION }}"
#          files: |
#            clickstream/build/outputs/aar/clickstream-release.aar
#          tag_name: "v${{ env.NEW_VERSION }}"
#          prerelease: true
#          generate_release_notes: true