name: Release Next Version
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release Tag'
        required: true
        type: string
env:
  NEW_VERSION: ${{ github.event.inputs.release_tag }}
jobs:
  release-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.PROJECT_TOKEN }}
      - name: Modify for next release
        run: |
          chmod +x release.sh
          ./release.sh ${{ env.NEW_VERSION }}
          git diff
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PROJECT_TOKEN }}
          commit-message: 'release: clickstream Android ${{ env.NEW_VERSION }}'
          title: 'release: clickstream Android ${{ env.NEW_VERSION }}'
          author: github-actions <github-actions@github.com>
          committer: github-actions <github-actions@github.com>
          signoff: true
          body: |
            - [x] PR title and description conform to [Pull Request](https://github.com/awslabs/clickstream-android/blob/main/CONTRIBUTING.md#pull-request-guidelines) guidelines.
            
            *Description of changes:*
            1. 'release: clickstream Android ${{ env.NEW_VERSION }}'
            
            *Documentation update required?*
            - [ ] No
            - [x] Yes (Please include a PR link for the documentation update)
  
            By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
          labels: release
          branch: release_${{ env.NEW_VERSION }}